  userdb:
    container_name: userdb
    image: mysql:8
    restart: always
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - dbuser:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    command: --default-authentication-plugin=mysql_native_password
