CREATE USER 'admdb'@'localhost' IDENTIFIED BY '123456789';
GRANT ALL PRIVILEGES ON *.* TO 'admdb'@'localhost' WITH GRANT OPTION;
CREATE USER 'admdb'@'%' IDENTIFIED BY '123456789';
GRANT ALL PRIVILEGES ON *.* TO 'admdb'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;