apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-mysql
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: garyjoan14/mysqlg1
        name: bdmysql
        ports:
        - containerPort: 3306
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: backend
spec:
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
    selector:
        app: mysql
    type: ClusterIP    
 