apiVersion: v1
kind: Service
metadata:
  name: node-svc
  namespace: backend
spec:
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    selector:
        app: node
    type: LoadBalancer    