apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-node
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - image: garyjoan14/apinode
        name: apinode
        ports:
        - containerPort: 80
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: node-svc
  namespace: backend
spec:
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    selector:
        app: node
    type: LoadBalancer    
 