apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-react
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - image: garyjoan14/webreact
        name: reactweb
        ports:
        - containerPort: 80
      restartPolicy: Always
